#!/usr/bin/env python3
"""
CyberLogia Agent Bootstrapper - automated security agent runner.
Service : System Hardening & CIS Compliance Check
Category: Blue Team

Lifecycle (runs identically on Linux, macOS and Windows):
  Phase 1  Dependency verification - stdlib check + requests bootstrap
  Phase 2  License check & payload fetch - GET /api/fetch-script
  Phase 3  Safe execution - runs the payload, errors never stop the loop
  Phase 4  Expiry / cancellation - HTTP 403 stops the agent cleanly
  Phase 5  Heartbeat loop - POST /api/heartbeat every 60 seconds

Usage:
    python agent_bootstrapper.py
"""

import datetime
import os
import platform
import socket
import subprocess
import sys
import time
import traceback

# --------------------------------------------------------------------------
# Configuration (generated by CyberLogia - do not edit by hand)
# --------------------------------------------------------------------------
BASE_URL = "http://127.0.0.1:8000"
SANCTUM_TOKEN = "11|RLfW7LbJF1IzLz9TpVyYtiQZgJXlnS81tdbLrq4y1c3d6b7a" or os.environ.get("SANCTUM_TOKEN", "")
SERVICE_ID = 2
LICENSE_KEY = "CWK-DE9NXYFYWVZRF6P7"
SERVICE_TITLE = "System Hardening & CIS Compliance Check"
SERVICE_CATEGORY = "Blue Team"
LICENSE_EXPIRES_AT = "2026-11-08T14:09:54+00:00" or None

FETCH_SCRIPT_ENDPOINT = BASE_URL + "/api/fetch-script"
HEARTBEAT_ENDPOINT = BASE_URL + "/api/heartbeat"
HEARTBEAT_INTERVAL = 60  # seconds between heartbeats

LINE = "=" * 68
TAG_OK = "[+]"
TAG_INFO = "[*]"
TAG_WARN = "[!]"
TAG_ERR = "[-]"

EXIT_OK = 0
EXIT_LICENSE = 3
EXIT_DEPENDENCY = 4
EXIT_NETWORK = 5

REQUIRED_STDLIB = (
    "json", "sys", "os", "time", "platform", "socket", "datetime",
)


# --------------------------------------------------------------------------
# Console helpers
# --------------------------------------------------------------------------
def banner(title):
    print("")
    print(LINE)
    print("  " + title)
    print(LINE)


def log(tag, message):
    print("%s %s" % (tag, message), flush=True)


def die(code, message):
    log(TAG_ERR, message)
    sys.exit(code)


# --------------------------------------------------------------------------
# Phase 1 - Dependency verification
# --------------------------------------------------------------------------
def phase_dependencies():
    """Verify the Python runtime and ensure `requests` is importable."""
    banner("Phase 1 - Dependency Verification")

    if sys.version_info < (3, 8):
        die(EXIT_DEPENDENCY,
            "Python 3.8 or newer is required (found %s)."
            % ".".join(str(part) for part in sys.version_info[:3]))

    log(TAG_OK, "Python %s on %s" % (platform.python_version(), sys.platform))

    missing = []
    for module in REQUIRED_STDLIB:
        try:
            __import__(module)
        except ImportError:
            missing.append(module)
    if missing:
        die(EXIT_DEPENDENCY,
            "Missing standard library modules: %s" % ", ".join(missing))
    log(TAG_OK, "All required standard library modules are present.")

    try:
        import requests  # noqa: F401
        log(TAG_OK, "Dependency 'requests' is already installed.")
        return True
    except ImportError:
        log(TAG_WARN, "Dependency 'requests' is missing - installing it now.")

    for command in (
        [sys.executable, "-m", "pip", "install", "--disable-pip-version-check",
         "--quiet", "requests"],
        [sys.executable, "-m", "pip", "install", "--user", "--quiet", "requests"],
        ["pip3", "install", "--quiet", "requests"],
        ["pip", "install", "--quiet", "requests"],
    ):
        try:
            log(TAG_INFO, "Running: %s" % " ".join(command))
            result = subprocess.run(command, capture_output=True, text=True)
            if result.returncode == 0:
                log(TAG_OK, "'requests' installed successfully.")
                break
            log(TAG_WARN, "pip exited with code %d." % result.returncode)
        except (OSError, ValueError) as exc:
            log(TAG_WARN, "Could not run pip: %s" % exc)

    try:
        import requests  # noqa: F401
        log(TAG_OK, "'requests' is now available.")
        return True
    except ImportError:
        die(EXIT_DEPENDENCY,
            "Unable to install 'requests'. Install it manually with "
            "'%s -m pip install requests' and re-run." % sys.executable)


# --------------------------------------------------------------------------
# Phase 2 - License check & payload fetch
# --------------------------------------------------------------------------
def api_headers():
    return {"Authorization": "Bearer " + SANCTUM_TOKEN, "Accept": "application/json"}


def fetch_script():
    """Validate the license and retrieve this service's script payload."""
    import requests

    banner("Phase 2 - License Check & Payload Fetch")
    log(TAG_INFO, "Service    : %s (%s)" % (SERVICE_TITLE, SERVICE_CATEGORY))
    log(TAG_INFO, "Service ID : %d" % SERVICE_ID)
    log(TAG_INFO, "Endpoint   : %s" % FETCH_SCRIPT_ENDPOINT)
    if LICENSE_EXPIRES_AT:
        log(TAG_INFO, "Expires at : %s" % LICENSE_EXPIRES_AT)

    try:
        response = requests.get(
            FETCH_SCRIPT_ENDPOINT,
            headers=api_headers(),
            params={"service_id": SERVICE_ID, "license_key": LICENSE_KEY},
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        die(EXIT_NETWORK, "Could not reach the CyberLogia API: %s" % exc)

    # Phase 4 - Expiry / cancellation handling.
    if response.status_code == 403:
        message = "License expired or invalid."
        try:
            body = response.json()
            message = body.get("message") or message
        except ValueError:
            pass
        banner("Agent Terminated - Renewal Required")
        log(TAG_ERR, "HTTP 403 - %s" % message)
        print("")
        print("  Your CyberLogia license for '%s' is no longer active." % SERVICE_TITLE)
        print("  The agent has stopped and will not collect any data.")
        print("")
        print("  Renew your subscription to resume operations:")
        print("    1. Visit %s/services" % BASE_URL)
        print("    2. Select '%s' and complete payment" % SERVICE_TITLE)
        print("    3. Download a fresh agent_bootstrapper.py from /my-tools")
        print("")
        sys.exit(EXIT_LICENSE)

    if response.status_code == 401:
        die(EXIT_LICENSE,
            "Authentication failed (HTTP 401). Download a fresh bootstrapper "
            "from /my-tools to refresh your API token.")
    if response.status_code == 404:
        die(EXIT_LICENSE,
            "No script is configured for this service yet. Please contact "
            "CyberLogia support.")
    if response.status_code != 200:
        die(EXIT_NETWORK,
            "Unexpected API response (HTTP %d)." % response.status_code)

    try:
        payload = response.json()
    except ValueError:
        die(EXIT_NETWORK, "The API returned a malformed response.")

    script_code = payload.get("script_code")
    if not script_code:
        die(EXIT_LICENSE, "The service returned an empty script payload.")

    log(TAG_OK, "License verified and payload retrieved (%d characters)."
        % len(script_code))
    return script_code


# --------------------------------------------------------------------------
# Phase 3 - Safe execution
# --------------------------------------------------------------------------
def execute_payload(script_code):
    """Run the retrieved payload in an isolated namespace.

    Errors are reported but never terminate the heartbeat loop.
    """
    banner("Phase 3 - Safe Execution")
    namespace = {
        "__name__": "__cyberlogia_agent__",
        "__builtins__": __builtins__,
        "SERVICE_ID": SERVICE_ID,
        "SERVICE_TITLE": SERVICE_TITLE,
        "BASE_URL": BASE_URL,
    }
    try:
        exec(compile(script_code, "<cyberlogia-payload>", "exec"), namespace)
        log(TAG_OK, "Payload execution finished successfully.")
        return True
    except SystemExit as exc:
        log(TAG_WARN, "Payload requested exit (code %s)." % exc.code)
    except KeyboardInterrupt:
        raise
    except Exception as exc:
        log(TAG_ERR, "Payload raised %s: %s" % (type(exc).__name__, exc))
        traceback.print_exc()
    return False


# --------------------------------------------------------------------------
# Phase 5 - Heartbeat
# --------------------------------------------------------------------------
def public_ip():
    """Best-effort local address reported with the heartbeat."""
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        try:
            sock.connect(("8.8.8.8", 80))
            return sock.getsockname()[0]
        finally:
            sock.close()
    except OSError:
        try:
            return socket.gethostbyname(socket.gethostname())
        except OSError:
            return "127.0.0.1"


def send_heartbeat():
    """Report liveness so the agent stays 'online' in the command center."""
    import requests
    try:
        requests.post(
            HEARTBEAT_ENDPOINT,
            headers=api_headers(),
            json={"service_id": SERVICE_ID, "ip_address": public_ip()},
            timeout=15,
        )
        return True
    except Exception:
        return False


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------
def main():
    banner("CyberLogia Automated Security Agent")
    print("  Service   : %s" % SERVICE_TITLE)
    print("  Category  : %s" % SERVICE_CATEGORY)
    print("  Platform  : %s (%s)" % (platform.platform(), sys.platform))
    print("  Started   : %s"
          % datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    print("")

    if not SANCTUM_TOKEN:
        die(EXIT_LICENSE,
            "No API token available. Set the SANCTUM_TOKEN environment "
            "variable or download a fresh bootstrapper from /my-tools.")

    phase_dependencies()
    script_code = fetch_script()

    if not execute_payload(script_code):
        log(TAG_WARN, "Payload reported a problem - continuing to monitor.")

    banner("Phase 5 - Heartbeat Loop")
    log(TAG_OK, "Agent is online. Heartbeat every %d seconds." % HEARTBEAT_INTERVAL)
    log(TAG_INFO, "Press Ctrl+C to stop the agent gracefully.")

    try:
        while True:
            if send_heartbeat():
                log(TAG_INFO, "Heartbeat acknowledged at %s"
                    % datetime.datetime.now().strftime("%H:%M:%S"))
            else:
                log(TAG_WARN, "Heartbeat failed - retrying in %ds."
                    % HEARTBEAT_INTERVAL)
            time.sleep(HEARTBEAT_INTERVAL)
    except KeyboardInterrupt:
        pass

    print("")
    log(TAG_OK, "Agent stopped. Goodbye.")


if __name__ == "__main__":
    main()